language: android
android:
  components:
  - android-23
  - build-tools-23.0.2

env:
- TRAVIS_NODE_VERSION="node"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm
    && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm
    install $TRAVIS_NODE_VERSION
  - npm install

script:
- node_modules/.bin/gulp build --phonegap
- node_modules/.bin/phonegap build android

cache:
  directories:
  - node_modules
  - platforms
  - plugins
  - www

deploy:
  provider: releases
  api_key:
    secure: f+TtTBFF3pTLa+pOpQhh3cybhq1JhMz3dAF/7fJy7EStHwbOuIEik9cg/2nwPCoXEy3P9no7F01Fi61He2SfiQJ2F9EE7xp70bbwkBVuL9tJri7UI5dZEykPVHQ1h25CvEDtpm2kqTPr89YBTjOJQ1n/hy3ty0wXH9hRzGlvRdssUnVMQ+6ICh82na03Enhb5GkX9g8KsWRN5JtBQCt9oPkjKo0LCI5JKyknUJcwUEveyCb+DXPH1/oDSWs0OTWv2MYVfu9qEwEsGm9WRKozJ6shGT6ZBnHiTuUjagMRqMMe1CT4yuV/9M00HVKhfDu2f529lJFXZJGAV2O+hRuI76hdaDizRrCBB8sS/V933dLw/P0Y3dHIs+hJQFZ4HM4E1XVWFkL+ADHK7tgNgm+ZWm3+Z4ZPj91ww3M3GscUldoEZNj8egiL/jOieeUx6RNKhtM8Ok7KCOq8z5bDR6CRhBKDpeuom5LiFzuhHpVJ8DCVvBQGGJSgWdlOJ1ggU1HWzP3MgArU49k26EGv8o/ytHMVVX9eQMDrZ8JZhkXNTMOC9xywMgzyqj8X7ii9Xla1MnGWqJy6+XV59cAMyJWfFx/YpJJZbXi0mUHT3KgCcDfZlddoDpqpxCWTfQ/8YMCFWu+8jeH8esOknFr1QcBkyGdVcXBNmvFI9izVCq8bUrk=
  file: platforms/android/build/outputs/apk/android-debug.apk
  skip_cleanup: true
  on:
    tags: true